graph LR
    EH[Entry Hall]<-->MH[Main Hall]
    EH[Entry Hall]<-->LR[Laundry]
    EH[Entry Hall]<-->K[Kitchen]
    K[Kitchen]<-->L[Living]
    MH[Main Hall]<-->GB[Guest Bath]
    MH[Main Hall]<-->BH[Back Hall]
    BH[Back Hall]<-->MO[Mom Office]
    BH[Back Hall]<-->DO[Dad Office]
    BH[Back Hall]<-->BB[Kid Bed]
    BH[Back Hall]<-->MB[Master Bed]
    MB[Master Bed]<-->MBR[Master Bath]
    BB[Kid Bed]<-->BC[Kid Closet]
    BB[Kid Bed]<-->BBR[Kid Bathroom]
